# Generated by Django 5.0.6 on 2024-06-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Почта"
                    ),
                ),
                (
                    "first_name",
                    models.ImageField(max_length=50, upload_to="", verbose_name="Имя"),
                ),
                (
                    "last_name",
                    models.ImageField(
                        max_length=50, upload_to="", verbose_name="Фамилия"
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to="users/", verbose_name="Аватар"
                    ),
                ),
                ("phone", models.CharField(max_length=35, verbose_name="Телефон")),
                (
                    "role",
                    models.ImageField(
                        blank=True,
                        max_length=50,
                        null=True,
                        upload_to="",
                        verbose_name="Роль",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True, default=True, null=True, verbose_name="Активно"
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
