# Generated by Django 5.0.6 on 2024-06-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_first_name_alter_user_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Роль"
            ),
        ),
    ]
