# Generated by Django 5.0.6 on 2024-06-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[("user", "User"), ("admin", "Admin")],
                default="user",
                max_length=50,
                null=True,
                verbose_name="Роль",
            ),
        ),
    ]
